### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ClydeNoIQ** [AIPTU/SimpleMotd#1]
If the author of this plugin is however active, I wanted to suggest making a countdown system and it can be customized through commands (Ex: /simplemotd countdown 12h)

It should look like this
![az_recorder_20230120_090652_edited](https://user-images.githubusercontent.com/86055764/215309884-188453bc-0dc7-431e-a172-cf854287cfa8.jpg)

I don't know if this is possible but i would be happy if it is

**Comment by AIPTU** [comment]
Hi!!! thanks for the advice. I was wondering what is the purpose of the countdown system you are referring to? Please explain more details about it to me.

**Comment by ClydeNoIQ** [comment]
I was talking about a timer feature for the MOTD plugin

There should be an available tag like: {COUNTDOWN} / {TIMER}, it could be customized through commands like (Ex: /simplemotd countdown 12) or config

There should be an (on the config)
- Ability to edit the timezone
- Ability to set any date, any time for the timer

My idea was originally from https://www.spigotmc.org/resources/motdcountdown.23249/ but i wanted it on PocketMine and i was wondering if it's possible
